### ISSUE TITLE
Release 1.1.7 incompatible with MC >= 1.19.3

### ISSUE THREAD

**Issue by SnuzzleWump** [0x4e49434f4c45/amcdb#29]
Since yesterday AMCDB has been sending this error whenever someone sends a message in minecraft chat. I think it is caused by something outside of the server as it is doing it on completely fresh servers. 

I don't know if Issues is the right place for this but I can't find anywhere else for it.

```
[22:34:36] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_44125()'
        at network.parthenon.amcdb.minecraft.InGameMessageHandler.handleChatMessage(InGameMessageHandler.java:45) ~[amcdb-1.1.7.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:103) ~[fabric-message-api-v1-5.1.7+3265161977-c3ab6ca4ce6148ea.jar:?]
        at net.minecraft.class_3324.handler$zdd000$fabric-message-api-v1$onSendChatMessage(class_3324.java:2035) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1429) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1303) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by 0x4e49434f4c45** [comment]
Issues is exactly the right place!

Hmm, what version of Minecraft are you running? Can you try grabbing the latest Fabric loader and Fabric API?

**Comment by SnuzzleWump** [comment]
I'm running 1.20.1, and I used the latest versions of both.

**Comment by 0x4e49434f4c45** [comment]
okay, I was able to reproduce this. It seems to be some type of mapping incompatibility introduced when I attempted to set the required Minecraft version down to 1.19.2.

I'll work on this, but in the meantime release [1.1.6](https://github.com/0x4e49434f4c45/amcdb/releases/tag/1.1.6) doesn't seem to have this problem and is nearly identical.

**Comment by SnuzzleWump** [comment]
ah okay, thank you
